#!/command/with-contenv bash
set -e

# Install the client private key
echo ${CLIENT_PRIVATE_KEY} > /private/wg1.key
wg-quick up wg1

# Forward ports to nginx proxy manager container
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 10.5.0.3:80
iptables -t nat -A POSTROUTING -p tcp -d 10.5.0.3 --dport 80 -j SNAT --to-source 127.0.0.1
iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 443 -j DNAT --to-destination 10.5.0.3:443

# Keep the service running
while true ; do 
    sleep 10
    wg show
done